package compose

import (
	"context"
	"fmt"
	"maps"
	"os"
	"path/filepath"

	"github.com/compose-spec/compose-go/v2/loader"
	"github.com/compose-spec/compose-go/v2/types"
)

// composeFileCandidates 常见的 compose 文件名（按优先级）
var composeFileCandidates = []string{
	"compose.yaml",
	"compose.yml",
	"docker-compose.yaml",
	"docker-compose.yml",
}

// ProjectToYAML 使用 compose-go 官方序列化器输出 YAML（带文件头）
func ProjectToYAML(project *types.Project) ([]byte, error) {
	if project == nil {
		return nil, fmt.Errorf("project 为空")
	}
	data, err := project.MarshalYAML()
	if err != nil {
		return nil, fmt.Errorf("序列化 compose 失败: %w", err)
	}
	return append([]byte("# Auto-generated by isrvd\n\n"), data...), nil
}

// LoadOptions 加载配置
type LoadOptions struct {
	// WorkingDir compose 文件所在目录（用于解析相对路径和 .env）
	WorkingDir string
	// ConfigFiles 指定要加载的 compose 文件绝对路径；为空则在 WorkingDir 下自动查找
	ConfigFiles []string
	// ProjectName 项目名（影响生成的网络/容器默认前缀）
	ProjectName string
	// Environment 额外的环境变量（会与 .env 合并，覆盖 .env）
	Environment map[string]string
}

// LoadProject 使用 compose-go 官方加载器解析 compose 文件，
// 自动处理 .env、变量插值、schema 校验等一致性检查
func LoadProject(ctx context.Context, opts LoadOptions) (*types.Project, error) {
	if opts.WorkingDir == "" {
		return nil, fmt.Errorf("缺少工作目录")
	}

	configFiles, err := resolveConfigFiles(opts.WorkingDir, opts.ConfigFiles)
	if err != nil {
		return nil, err
	}
	files, err := readConfigFiles(configFiles)
	if err != nil {
		return nil, err
	}

	projectName := opts.ProjectName
	if projectName == "" {
		projectName = filepath.Base(opts.WorkingDir)
	}

	return loadProject(ctx, types.ConfigDetails{
		WorkingDir:  opts.WorkingDir,
		ConfigFiles: files,
		Environment: projectEnvironment(opts.Environment),
	}, projectName, true, true)
}

// LoadProjectFromContent 从 yaml 文本直接加载 compose 项目
// 用于「手动粘贴 compose 内容」场景，临时写入内存 buffer 即可
func LoadProjectFromContent(ctx context.Context, content string, projectName string) (*types.Project, error) {
	if content == "" {
		return nil, fmt.Errorf("compose 内容为空")
	}

	details := types.ConfigDetails{
		WorkingDir: ".",
		ConfigFiles: []types.ConfigFile{
			{
				Filename: "compose.yml",
				Content:  []byte(content),
			},
		},
		Environment: projectEnvironment(nil),
	}

	return loadProject(ctx, details, projectName, false, projectName != "")
}

func loadProject(ctx context.Context, details types.ConfigDetails, projectName string, resolvePaths bool, setProjectName bool) (*types.Project, error) {
	projectName = loader.NormalizeProjectName(projectName)
	project, err := loader.LoadWithContext(ctx, details, func(o *loader.Options) {
		if setProjectName && projectName != "" {
			o.SetProjectName(projectName, true)
		}
		o.SkipConsistencyCheck = false
		o.SkipValidation = false
		o.ResolvePaths = resolvePaths
	})
	if err != nil {
		return nil, fmt.Errorf("加载 compose 失败: %w", err)
	}
	return project, nil
}

func projectEnvironment(extra map[string]string) map[string]string {
	env := make(map[string]string)
	for _, e := range os.Environ() {
		for i := 0; i < len(e); i++ {
			if e[i] == '=' {
				env[e[:i]] = e[i+1:]
				break
			}
		}
	}
	maps.Copy(env, extra)
	return env
}
func resolveConfigFiles(workingDir string, configFiles []string) ([]string, error) {
	if len(configFiles) > 0 {
		return configFiles, nil
	}
	found, err := locateComposeFile(workingDir)
	if err != nil {
		return nil, err
	}
	return []string{found}, nil
}

func readConfigFiles(paths []string) ([]types.ConfigFile, error) {
	files := make([]types.ConfigFile, 0, len(paths))
	for _, p := range paths {
		data, err := os.ReadFile(p)
		if err != nil {
			return nil, fmt.Errorf("读取 compose 文件失败: %w", err)
		}
		files = append(files, types.ConfigFile{Filename: p, Content: data})
	}
	return files, nil
}

// locateComposeFile 在指定目录下查找 compose 文件
// 查找顺序：根目录 → 一级子目录（处理 zip 解压后外层多一层目录的情况）
func locateComposeFile(dir string) (string, error) {
	if p, ok := findComposeFile(dir); ok {
		return p, nil
	}

	entries, err := os.ReadDir(dir)
	if err != nil {
		return "", fmt.Errorf("读取目录失败: %w", err)
	}
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		if p, ok := findComposeFile(filepath.Join(dir, e.Name())); ok {
			return p, nil
		}
	}
	return "", fmt.Errorf("目录中未找到 compose 文件")
}

func findComposeFile(dir string) (string, bool) {
	for _, name := range composeFileCandidates {
		p := filepath.Join(dir, name)
		if st, err := os.Stat(p); err == nil && !st.IsDir() {
			return p, true
		}
	}
	return "", false
}
